-- P104 V2 WhisperTour
-- This version does not require new database tables.
-- Captions use Supabase Realtime Broadcast public channels.
-- Voice uses LiveKit. LiveKit access tokens are generated by the P104_V2_livekit_token Edge Function.

-- If Supabase Realtime Broadcast returns CHANNEL_ERROR:
-- 1. Check config.js SUPABASE_URL. It must be https://xxxxx.supabase.co, not /rest/v1/.
-- 2. Make sure Realtime service is enabled.
-- 3. Make sure public channels are allowed, unless you rewrite the app to use private channels.
-- 4. Force refresh Chrome with Ctrl + F5 after editing config.js.
